AllCops:
  DisplayCopNames: true

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Security/Eval:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false
